
    var $m = Bridge.setMetadata,
        $n = ["System","Newtonsoft.Json.Serialization","Newtonsoft.Json"];
    $m("Newtonsoft.Json.JsonException", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":".ctor","t":1,"p":[$n[0].String],"pi":[{"n":"message","pt":$n[0].String,"ps":0}],"sn":"$ctor1"},{"a":2,"n":".ctor","t":1,"p":[$n[0].String,$n[0].Exception],"pi":[{"n":"message","pt":$n[0].String,"ps":0},{"n":"innerException","pt":$n[0].Exception,"ps":1}],"sn":"$ctor2"}]}; }, $n);
    $m("Newtonsoft.Json.JsonSerializationException", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":".ctor","t":1,"p":[$n[0].String],"pi":[{"n":"message","pt":$n[0].String,"ps":0}],"sn":"$ctor1"},{"a":2,"n":".ctor","t":1,"p":[$n[0].String,$n[0].Exception],"pi":[{"n":"message","pt":$n[0].String,"ps":0},{"n":"innerException","pt":$n[0].Exception,"ps":1}],"sn":"$ctor2"}]}; }, $n);
    $m("Newtonsoft.Json.JsonSerializerSettings", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"ContractResolver","t":16,"rt":$n[1].IContractResolver,"g":{"a":2,"n":"get_ContractResolver","t":8,"rt":$n[1].IContractResolver,"fg":"ContractResolver"},"s":{"a":2,"n":"set_ContractResolver","t":8,"p":[$n[1].IContractResolver],"rt":$n[0].Void,"fs":"ContractResolver"},"fn":"ContractResolver"},{"a":2,"n":"NullValueHandling","t":16,"rt":$n[2].NullValueHandling,"g":{"a":2,"n":"get_NullValueHandling","t":8,"rt":$n[2].NullValueHandling,"fg":"NullValueHandling","box":function ($v) { return Bridge.box($v, Newtonsoft.Json.NullValueHandling, System.Enum.toStringFn(Newtonsoft.Json.NullValueHandling));}},"s":{"a":2,"n":"set_NullValueHandling","t":8,"p":[$n[2].NullValueHandling],"rt":$n[0].Void,"fs":"NullValueHandling"},"fn":"NullValueHandling"},{"a":2,"n":"TypeNameHandling","t":16,"rt":$n[2].TypeNameHandling,"g":{"a":2,"n":"get_TypeNameHandling","t":8,"rt":$n[2].TypeNameHandling,"fg":"TypeNameHandling","box":function ($v) { return Bridge.box($v, Newtonsoft.Json.TypeNameHandling, System.Enum.toStringFn(Newtonsoft.Json.TypeNameHandling));}},"s":{"a":2,"n":"set_TypeNameHandling","t":8,"p":[$n[2].TypeNameHandling],"rt":$n[0].Void,"fs":"TypeNameHandling"},"fn":"TypeNameHandling"},{"a":4,"n":"DefaultNullValueHandling","is":true,"t":4,"rt":$n[2].NullValueHandling,"sn":"DefaultNullValueHandling","box":function ($v) { return Bridge.box($v, Newtonsoft.Json.NullValueHandling, System.Enum.toStringFn(Newtonsoft.Json.NullValueHandling));}},{"a":4,"n":"DefaultTypeNameHandling","is":true,"t":4,"rt":$n[2].TypeNameHandling,"sn":"DefaultTypeNameHandling","box":function ($v) { return Bridge.box($v, Newtonsoft.Json.TypeNameHandling, System.Enum.toStringFn(Newtonsoft.Json.TypeNameHandling));}},{"a":4,"n":"_nullValueHandling","t":4,"rt":$n[0].Nullable$1(Newtonsoft.Json.NullValueHandling),"sn":"_nullValueHandling","box":function ($v) { return Bridge.box($v, Newtonsoft.Json.NullValueHandling, System.Nullable.toStringFn(System.Enum.toStringFn(Newtonsoft.Json.NullValueHandling)), System.Nullable.getHashCode);}},{"a":4,"n":"_typeNameHandling","t":4,"rt":$n[0].Nullable$1(Newtonsoft.Json.TypeNameHandling),"sn":"_typeNameHandling","box":function ($v) { return Bridge.box($v, Newtonsoft.Json.TypeNameHandling, System.Nullable.toStringFn(System.Enum.toStringFn(Newtonsoft.Json.TypeNameHandling)), System.Nullable.getHashCode);}},{"a":1,"backing":true,"n":"<ContractResolver>k__BackingField","t":4,"rt":$n[1].IContractResolver,"sn":"ContractResolver"}]}; }, $n);
    $m("Newtonsoft.Json.NullValueHandling", function () { return {"att":257,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Ignore","is":true,"t":4,"rt":$n[2].NullValueHandling,"sn":"Ignore","box":function ($v) { return Bridge.box($v, Newtonsoft.Json.NullValueHandling, System.Enum.toStringFn(Newtonsoft.Json.NullValueHandling));}},{"a":2,"n":"Include","is":true,"t":4,"rt":$n[2].NullValueHandling,"sn":"Include","box":function ($v) { return Bridge.box($v, Newtonsoft.Json.NullValueHandling, System.Enum.toStringFn(Newtonsoft.Json.NullValueHandling));}}]}; }, $n);
    $m("Newtonsoft.Json.JsonConstructorAttribute", function () { return {"att":1048833,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"}]}; }, $n);
    $m("Newtonsoft.Json.Formatting", function () { return {"att":257,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Indented","is":true,"t":4,"rt":$n[2].Formatting,"sn":"Indented","box":function ($v) { return Bridge.box($v, Newtonsoft.Json.Formatting, System.Enum.toStringFn(Newtonsoft.Json.Formatting));}},{"a":2,"n":"None","is":true,"t":4,"rt":$n[2].Formatting,"sn":"None","box":function ($v) { return Bridge.box($v, Newtonsoft.Json.Formatting, System.Enum.toStringFn(Newtonsoft.Json.Formatting));}}]}; }, $n);
    $m("Newtonsoft.Json.TypeNameHandling", function () { return {"att":257,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"None","is":true,"t":4,"rt":$n[2].TypeNameHandling,"sn":"None","box":function ($v) { return Bridge.box($v, Newtonsoft.Json.TypeNameHandling, System.Enum.toStringFn(Newtonsoft.Json.TypeNameHandling));}},{"a":2,"n":"Objects","is":true,"t":4,"rt":$n[2].TypeNameHandling,"sn":"Objects","box":function ($v) { return Bridge.box($v, Newtonsoft.Json.TypeNameHandling, System.Enum.toStringFn(Newtonsoft.Json.TypeNameHandling));}}]}; }, $n);
    $m("Newtonsoft.Json.Utils.AssemblyVersion", function () { return {"att":1048576,"a":4,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"compiler","is":true,"t":4,"rt":$n[0].String,"sn":"compiler"},{"a":2,"n":"version","is":true,"t":4,"rt":$n[0].String,"sn":"version"}]}; }, $n);
    $m("Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"}]}; }, $n);
    $m("Newtonsoft.Json.Serialization.IContractResolver", function () { return {"att":161,"a":2}; }, $n);
