
    var $m = Bridge.setMetadata,
        $n = [Newtonsoft.Json.Serialization,System,Newtonsoft.Json];
    $m($n[2].JsonSerializerSettings, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"ContractResolver","t":16,"rt":$n[0].IContractResolver,"g":{"a":2,"n":"get_ContractResolver","t":8,"rt":$n[0].IContractResolver,"fg":"ContractResolver"},"s":{"a":2,"n":"set_ContractResolver","t":8,"p":[$n[0].IContractResolver],"rt":$n[1].Void,"fs":"ContractResolver"},"fn":"ContractResolver"},{"a":2,"n":"NullValueHandling","t":16,"rt":$n[2].NullValueHandling,"g":{"a":2,"n":"get_NullValueHandling","t":8,"rt":$n[2].NullValueHandling,"fg":"NullValueHandling"},"s":{"a":2,"n":"set_NullValueHandling","t":8,"p":[$n[2].NullValueHandling],"rt":$n[1].Void,"fs":"NullValueHandling"},"fn":"NullValueHandling"},{"a":2,"n":"TypeNameHandling","t":16,"rt":$n[2].TypeNameHandling,"g":{"a":2,"n":"get_TypeNameHandling","t":8,"rt":$n[2].TypeNameHandling,"fg":"TypeNameHandling"},"s":{"a":2,"n":"set_TypeNameHandling","t":8,"p":[$n[2].TypeNameHandling],"rt":$n[1].Void,"fs":"TypeNameHandling"},"fn":"TypeNameHandling"},{"a":4,"n":"DefaultNullValueHandling","is":true,"t":4,"rt":$n[2].NullValueHandling,"sn":"DefaultNullValueHandling"},{"a":4,"n":"DefaultTypeNameHandling","is":true,"t":4,"rt":$n[2].TypeNameHandling,"sn":"DefaultTypeNameHandling"},{"a":4,"n":"_nullValueHandling","t":4,"rt":$n[1].Nullable$1(Newtonsoft.Json.NullValueHandling),"sn":"_nullValueHandling"},{"a":4,"n":"_typeNameHandling","t":4,"rt":$n[1].Nullable$1(Newtonsoft.Json.TypeNameHandling),"sn":"_typeNameHandling"}]}; });
    $m($n[2].NullValueHandling, function () { return {"att":257,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Ignore","is":true,"t":4,"rt":$n[2].NullValueHandling,"sn":"Ignore"},{"a":2,"n":"Include","is":true,"t":4,"rt":$n[2].NullValueHandling,"sn":"Include"}]}; });
    $m($n[2].Formatting, function () { return {"att":257,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Indented","is":true,"t":4,"rt":$n[2].Formatting,"sn":"Indented"},{"a":2,"n":"None","is":true,"t":4,"rt":$n[2].Formatting,"sn":"None"}]}; });
    $m($n[2].TypeNameHandling, function () { return {"att":257,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"All","is":true,"t":4,"rt":$n[2].TypeNameHandling,"sn":"All"},{"a":2,"n":"Arrays","is":true,"t":4,"rt":$n[2].TypeNameHandling,"sn":"Arrays"},{"a":2,"n":"Auto","is":true,"t":4,"rt":$n[2].TypeNameHandling,"sn":"Auto"},{"a":2,"n":"None","is":true,"t":4,"rt":$n[2].TypeNameHandling,"sn":"None"},{"a":2,"n":"Objects","is":true,"t":4,"rt":$n[2].TypeNameHandling,"sn":"Objects"}]}; });
    $m($n[0].CamelCasePropertyNamesContractResolver, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[0].IContractResolver, function () { return {"att":161,"a":2}; });
