
    var $m = Bridge.setMetadata,
        $n = [System,Newtonsoft.Json.Serialization,Newtonsoft.Json];
    $m($n[2].JsonException, function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":".ctor","t":1,"p":[$n[0].String],"pi":[{"n":"message","pt":$n[0].String,"ps":0}],"sn":"$ctor1"},{"a":2,"n":".ctor","t":1,"p":[$n[0].String,$n[0].Exception],"pi":[{"n":"message","pt":$n[0].String,"ps":0},{"n":"innerException","pt":$n[0].Exception,"ps":1}],"sn":"$ctor2"}]}; });
    $m($n[2].JsonSerializationException, function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":".ctor","t":1,"p":[$n[0].String],"pi":[{"n":"message","pt":$n[0].String,"ps":0}],"sn":"$ctor1"},{"a":2,"n":".ctor","t":1,"p":[$n[0].String,$n[0].Exception],"pi":[{"n":"message","pt":$n[0].String,"ps":0},{"n":"innerException","pt":$n[0].Exception,"ps":1}],"sn":"$ctor2"}]}; });
    $m($n[2].JsonSerializerSettings, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"ContractResolver","t":16,"rt":$n[1].IContractResolver,"g":{"a":2,"n":"get_ContractResolver","t":8,"rt":$n[1].IContractResolver,"fg":"ContractResolver"},"s":{"a":2,"n":"set_ContractResolver","t":8,"p":[$n[1].IContractResolver],"rt":$n[0].Void,"fs":"ContractResolver"},"fn":"ContractResolver"},{"a":2,"n":"NullValueHandling","t":16,"rt":$n[2].NullValueHandling,"g":{"a":2,"n":"get_NullValueHandling","t":8,"rt":$n[2].NullValueHandling,"fg":"NullValueHandling"},"s":{"a":2,"n":"set_NullValueHandling","t":8,"p":[$n[2].NullValueHandling],"rt":$n[0].Void,"fs":"NullValueHandling"},"fn":"NullValueHandling"},{"a":2,"n":"TypeNameHandling","t":16,"rt":$n[2].TypeNameHandling,"g":{"a":2,"n":"get_TypeNameHandling","t":8,"rt":$n[2].TypeNameHandling,"fg":"TypeNameHandling"},"s":{"a":2,"n":"set_TypeNameHandling","t":8,"p":[$n[2].TypeNameHandling],"rt":$n[0].Void,"fs":"TypeNameHandling"},"fn":"TypeNameHandling"},{"a":4,"n":"DefaultNullValueHandling","is":true,"t":4,"rt":$n[2].NullValueHandling,"sn":"DefaultNullValueHandling"},{"a":4,"n":"DefaultTypeNameHandling","is":true,"t":4,"rt":$n[2].TypeNameHandling,"sn":"DefaultTypeNameHandling"},{"a":4,"n":"_nullValueHandling","t":4,"rt":$n[0].Nullable$1(Newtonsoft.Json.NullValueHandling),"sn":"_nullValueHandling"},{"a":4,"n":"_typeNameHandling","t":4,"rt":$n[0].Nullable$1(Newtonsoft.Json.TypeNameHandling),"sn":"_typeNameHandling"}]}; });
    $m($n[2].NullValueHandling, function () { return {"att":257,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Ignore","is":true,"t":4,"rt":$n[2].NullValueHandling,"sn":"Ignore"},{"a":2,"n":"Include","is":true,"t":4,"rt":$n[2].NullValueHandling,"sn":"Include"}]}; });
    $m($n[2].Formatting, function () { return {"att":257,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Indented","is":true,"t":4,"rt":$n[2].Formatting,"sn":"Indented"},{"a":2,"n":"None","is":true,"t":4,"rt":$n[2].Formatting,"sn":"None"}]}; });
    $m($n[2].TypeNameHandling, function () { return {"att":257,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"None","is":true,"t":4,"rt":$n[2].TypeNameHandling,"sn":"None"},{"a":2,"n":"Objects","is":true,"t":4,"rt":$n[2].TypeNameHandling,"sn":"Objects"}]}; });
    $m($n[1].CamelCasePropertyNamesContractResolver, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[1].IContractResolver, function () { return {"att":161,"a":2}; });
